### ISSUE TITLE
error with getCurves

### ISSUE THREAD

**Issue by farrokh** [stefanprokopdev/verify-apple-id-token#124]
Hi,

I'm using your package with NextJS. when I run it I get the following error:
````
Unhandled Runtime Error
TypeError: getCurves is not a function
```
and the error handler point to `const verifyAppleToken = require("verify-apple-id-token").default;`

**Comment by stefanprokopdev** [comment]
Hey @farrokh 

thanks for the issue.

NextJS is frontend framework right? This library should be used on Node.js server - it is backend side library which takes apple token from frontend login process and verifies it against apple servers, if you look here: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user. It is prepared for the `API server` and `Apple ID server` side, not the `App` side. So please make sure, you use it on the server, not on the frontend.

Because when I quickly googled the `getCurves` function, it's available in Node.js and that is maybe the problem because Node.js features are not available on frontend. But I am not sure where the `getCurves` comes from at the moment.

If you use the lib on the backend / server side, could you please share the whole stack trace and include the exact "minimal working example" for your issue? :pray:

**Comment by farrokh** [comment]
Duplicate of 

> Hey @farrokh
> 
> thanks for the issue.
> 
> NextJS is frontend framework right? This library should be used on Node.js server - it is backend side library which takes apple token from frontend login process and verifies it against apple servers, if you look here: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user. It is prepared for the `API server` and `Apple ID server` side, not the `App` side. So please make sure, you use it on the server, not on the frontend.
> 
> Because when I quickly googled the `getCurves` function, it's available in Node.js and that is maybe the problem because Node.js features are not available on frontend. But I am not sure where the `getCurves` comes from at the moment.
> 
> If you use the lib on the backend / server side, could you please share the whole stack trace and include the exact "minimal working example" for your issue? 🙏

Hey,

Yes I figured it out last night! I moved the code to API side and works fine now. Thanks again for your time.

**Comment by stefanprokopdev** [comment]
Thanks for the response! Perfect, hope it is now all good! Let me know when there are some problems! :slightly_smiling_face:
